server:
  port: 8101
spring:
  application:
    name: config
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/javahyy/cloud-config-repo #配置git仓库地址目录 https://github.com/javahyy/cloud-config-repo.git
#          searchPaths: cloud-demo #配置仓库路径
          searchPaths: cloud-demo/config #配置仓库路径
          username: javahyy #访问git仓库的用户名
          password: hy11203080311 #访问git仓库的用户密码
          basedir: /Users/mac/Documents/idea/github/cloud-demo/config/src/main/resources/config-local #保存到本地

      label: master #配置仓库的分支
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest
#    virtualHost: /
#    publisherConfirms: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,bus-refresh